name: Build & Release

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 * * * *" 

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/catppuccin/userstyles.git
          git fetch upstream main

      - id: check
        name: Check if upstream has new commits
        run: |
          LOCAL_SHA=$(git rev-parse origin/main)
          UPSTREAM_SHA=$(git rev-parse upstream/main)
          echo "Local main:    $LOCAL_SHA"
          echo "Upstream main: $UPSTREAM_SHA"
          if [ "$LOCAL_SHA" != "$UPSTREAM_SHA" ]; then
            echo "Upstream has new commits."
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "No new commits upstream. Skipping build."
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-upstream
    if: needs.check-upstream.outputs.should_run == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Fetch upstream repo
        run: |
          git remote add upstream https://github.com/catppuccin/userstyles.git
          git fetch upstream main

      - name: Sync specified files from upstream
        run: |
          git checkout upstream/main -- \
            .github/CODEOWNERS \
            .github/issue-labeler.yml \
            .github/pr-labeler.yml \
            styles/
          echo "Synced specified files from upstream"

      - name: Apply patches
        run: |
          chmod +x ./scripts/automation/style-patch.sh
          ./scripts/automation/style-patch.sh

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/CODEOWNERS .github/issue-labeler.yml .pr-labeler.yml styles/ || true
          git add -u || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: sync with upstream & apply patches"
            git push origin HEAD:main
          fi

      - name: Setup Deno
        uses: nekowinston/setup-deno@main
        with:
          deno-version: v2.3.5

      - name: Generate Stylus import
        run: deno task ci:stylus-import

      - name: Publish rolling release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: rolling
          name: Rolling Release
          body: "Automated build patched for everforst, from upstream catppuchin main branch."
          files: dist/import.json
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

